[package]
name = "Orinium_Browser"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD

=======
rand = "0.8.5"
softbuffer = "0.4.1"
tiny-skia = "0.11.4"
winit = "0.29.15"
>>>>>>> 850d6e8411f9468b46e8ca9812a62a4531b30889

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
